routes/web.php
<?php

use App\Repositories\Models\Role;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    return view('welcome');
    return redirect()->route('products.index',1);

});
//Route::get('user/dashboard/test','Manegment\Users\Dashboard\DashboardController@index')->name('dashboard');


Auth::routes();

Route::get('/home', function (){
    return redirect()->route('products.index',3);
})->name('home');
//Route::get('/home', 'HomeController@index')->name('home');


Route::prefix('products')->name('products.')->group(function (){
    Route::get('/category/{category}','Web\Products\ProductsController@index')->name('index');
});

Route::prefix('basket')->name('basket.')->group(function (){
    Route::get('/add/product/{product}/{prescription}/{seller}','Web\Basket\BasketController@add')->name('add');
    Route::get('/','Web\Basket\BasketController@index')->name('index');
    Route::post('/update/{product}/{seller}','Web\Basket\BasketController@update')->name('update');
    Route::get('/checkout','Web\Basket\BasketController@checkOutForm')->name('checkout.form');
    Route::post('/checkout','Web\Basket\BasketController@checkOut')->name('checkout');
});

Route::prefix('accounting')->name('accounting.')->group(function (){
    Route::prefix('payment')->name('payment.')->group(function (){
        Route::post('{gateway}/callback','Web\Accounting\PaymentController@verify')->name('verify');
    });
});

//Route::get('/getCity','Manegment\CityQuarterController@getCity')->name('get.city');

Route::get('basket/clear', function (){
    resolve(\App\Support\Storage\Contracts\StorageInterface::class)->clear();
});

resources/views/web/them/partials/desktopSiteHeader.blade.php
<header class="site__header d-lg-block d-none">
    <div class="site-header">
        <!-- .topbar -->
    @include('web.them.partials.desktopSiteHeader.topbar')
    <!-- .topbar / end -->
        @include('web.them.partials.desktopSiteHeader.siteHeaderMiddleContainer')

        <div class="site-header__nav-panel">
            <div class="nav-panel">
                <div class="nav-panel__container container">
                    <div class="nav-panel__row">
                        <div class="nav-panel__departments">
                            <!-- .departments -->
                        @include('web.them.partials.desktopSiteHeader.navPanelDepartments')
                        <!-- .departments / end -->
                        </div>
                        <!-- .nav-links -->
                    @include('web.them.partials.desktopSiteHeader.navLinks')
                    <!-- .nav-links / end -->
                        @include('web.them.partials.desktopSiteHeader.navPanelIndicators')
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/web/them/partials/dropcart.blade.php
<div class="dropcart">
{{--    <div class="dropcart__products-list">--}}
{{--        <div class="dropcart__product">--}}
{{--            <div class="dropcart__product-image">--}}
{{--                <a href="product.html"><img src="{{ asset('assets/them/images/products/product-1.jpg')}}" alt=""></a>--}}
{{--            </div>--}}
{{--            <div class="dropcart__product-info">--}}
{{--                <div class="dropcart__product-name"><a href="product.html">اره برقی برندیکس مدل 300 وات</a></div>--}}
{{--                <ul class="dropcart__product-options">--}}
{{--                    <li>رنگ: زرد</li>--}}
{{--                    <li>جنس: آلومینیوم</li>--}}
{{--                </ul>--}}
{{--                <div class="dropcart__product-meta"><span class="dropcart__product-quantity">2</span> × <span class="dropcart__product-price">699,000 تومان</span></div>--}}
{{--            </div>--}}
{{--            <button type="button" class="dropcart__product-remove btn btn-light btn-sm btn-svg-icon">--}}
{{--                <svg width="10px" height="10px">--}}
{{--                    <use xlink:href="{{ asset('assets/them/images/sprite.svg#cross-10')}}"></use>--}}
{{--                </svg>--}}
{{--            </button>--}}
{{--        </div>--}}
{{--        <div class="dropcart__product">--}}
{{--            <div class="dropcart__product-image">--}}
{{--                <a href="product.html"><img src="{{ asset('assets/them/images/products/product-2.jpg')}}" alt=""></a>--}}
{{--            </div>--}}
{{--            <div class="dropcart__product-info">--}}
{{--                <div class="dropcart__product-name"><a href="product.html">اره چوب بری IRadix مدل 2700 وات</a></div>--}}
{{--                <div class="dropcart__product-meta"><span class="dropcart__product-quantity">1</span> × <span class="dropcart__product-price">849,000 تومان</span></div>--}}
{{--            </div>--}}
{{--            <button type="button" class="dropcart__product-remove btn btn-light btn-sm btn-svg-icon">--}}
{{--                <svg width="10px" height="10px">--}}
{{--                    <use xlink:href="{{ asset('assets/them/images/sprite.svg#cross-10')}}"></use>--}}
{{--                </svg>--}}
{{--            </button>--}}
{{--        </div>--}}
{{--        <div class="dropcart__product">--}}
{{--            <div class="dropcart__product-image">--}}
{{--                <a href="product.html"><img src="{{ asset('assets/them/images/products/product-5.jpg')}}" alt=""></a>--}}
{{--            </div>--}}
{{--            <div class="dropcart__product-info">--}}
{{--                <div class="dropcart__product-name"><a href="product.html">میخ کوب برقی برندیکس مدل 2019</a></div>--}}
{{--                <ul class="dropcart__product-options">--}}
{{--                    <li>رنگ: قرمز</li>--}}
{{--                </ul>--}}
{{--                <div class="dropcart__product-meta"><span class="dropcart__product-quantity">3</span> × <span class="dropcart__product-price">1,210,000 تومان</span></div>--}}
{{--            </div>--}}
{{--            <button type="button" class="dropcart__product-remove btn btn-light btn-sm btn-svg-icon">--}}
{{--                <svg width="10px" height="10px">--}}
{{--                    <use xlink:href="{{ asset('assets/them/images/sprite.svg#cross-10')}}"></use>--}}
{{--                </svg>--}}
{{--            </button>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--    <div class="dropcart__totals">--}}
{{--        <table>--}}
{{--            <tr>--}}
{{--                <th>جمع جزء</th>--}}
{{--                <td>5,877,000 تومان</td>--}}
{{--            </tr>--}}
{{--            <tr>--}}
{{--                <th>حمل و نقل</th>--}}
{{--                <td>25,000 تومان</td>--}}
{{--            </tr>--}}
{{--            <tr>--}}
{{--                <th>مالیات</th>--}}
{{--                <td>0 تومان</td>--}}
{{--            </tr>--}}
{{--            <tr>--}}
{{--                <th>جمع کل</th>--}}
{{--                <td>5,902,000 تومان</td>--}}
{{--            </tr>--}}
{{--        </table>--}}
{{--    </div>--}}
    <div class="dropcart__buttons">
        <a class="btn btn-secondary" href="{{route('basket.index')}}">مشاهده سبد</a>
{{--        <a class="btn btn-primary" href="checkout.html">پرداخت</a>--}}
    </div>
</div>

resources/views/web/them/partials/footer.blade.php
<footer class="site__footer">
    <div class="site-footer">
        <div class="container">
            <div class="site-footer__widgets">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="site-footer__widget footer-contacts">
                            <h5 class="footer-contacts__title">تاسیس داروخانه
                            </h5>
                            <div class="footer-contacts__text">
                                داروخانه با بیش از 50 سال سابقه فعالیت عرضه داروهای تخصصی و همچنین فروش لوازم آرایشی، بهداشتی مورد تأیید وزارت بهداشت و مو، ناخن و زیبائی یکی از معدود داروخانه های پیشرو در ارائه خدمات نوین بمنظور ارتقاء سطح بهداشت و سلامت جامعه می باشد ، همچنین ساخت نسخ ترکیبی پوست و مو با مواد اولیه با کیفیت بالا یکی از زمینه های عرضه خدمات داروخانه می باشد.


                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-md-3 col-lg-2">
                        <div class="site-footer__widget footer-links">
                            <h5 class="footer-links__title">آدرس داروخانه
                            </h5>
                            <ul class="footer-links__list">
                                <li class="footer-links__item"><a href="" class="footer-links__link">
                                        قم - باجک -کوچه45
                                    </a></li>
                                <li class="footer-links__item"><a href="" class="footer-links__link">
                                        تلفن : 0253 -1223456
                                    </a></li>
                                <li class="footer-links__item"><a href="" class="footer-links__link">
                                        ایمیل : b@a.com
                                    </a></li>
                            </ul>
                            <div>
                                <img src="{{asset('assets/them/images/logos/logo.png')}}" class="img-sm" width="150px" height="100px">

                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-md-12 col-lg-4">
                        <div class="site-footer__widget footer-newsletter">
                            <h5 class="footer-newsletter__title">خبرنامه</h5>
                            <div class="footer-newsletter__text">
                                سازمان جهانی بهداشت اعلام کرده آزمایش ۳ داروی هیدروکسی کلروکین، لوپیناویر و ریتوناویر برای درمان بیماران مبتلا به کووید۱۹ در بیمارستان را متوقف کرده است.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="site-footer__bottom">
{{--                <div class="site-footer__copyright">ارائه شده در وب‌سایت <a href="https://www.rtl-theme.com"--}}
{{--                                                                            target="_blank">راست‌چین</a></div>--}}
{{--                <div class="site-footer__payments"><img src="{{ asset('assets/them/images/payments.png')}}" alt="">--}}
{{--                </div>--}}
            </div>
        </div>
    </div>
</footer>

resources/views/web/them/partials/head.blade.php
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="format-detection" content="telephone=no">
<title>@section('title'){{ config('app.name', 'Laravel') }}@show</title>
<link rel="icon" type="image/png" href="{{ asset('assets/them/images/favicon.png')}}">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}"/>

<!-- css -->
<link rel="stylesheet" href="{{ asset('assets/them/vendor/bootstrap-4.2.1/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{ asset('assets/them/vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{ asset('assets/them/vendor/lightgallery-1.6.12/css/lightgallery.min.css')}}">
<link rel="stylesheet" href="{{ asset('assets/them/css/style.css')}}">
<link rel="stylesheet" href="{{ asset('assets/them/css/custom.css')}}">
<!-- js -->
<script src="{{ asset('assets/them/vendor/jquery-3.3.1/jquery.min.j')}}s"></script>
<script src="{{ asset('assets/them/vendor/bootstrap-4.2.1/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{ asset('assets/them/vendor/owl-carousel-2.3.4/owl.carousel.min.js')}}"></script>
<script src="{{ asset('assets/them/vendor/nouislider-12.1.0/nouislider.min.js')}}"></script>
<script src="{{ asset('assets/them/vendor/lightgallery-1.6.12/js/lightgallery.min.js')}}"></script>
<script src="{{ asset('assets/them/vendor/lightgallery-1.6.12/js/lg-thumbnail.min.js')}}"></script>
<script src="{{ asset('assets/them/vendor/lightgallery-1.6.12/js/lg-zoom.min.js')}}"></script>
<script src="{{ asset('assets/them/js/number.js')}}"></script>
<script src="{{ asset('assets/them/js/main.js')}}"></script>
<script src="{{ asset('assets/them/vendor/svg4everybody-2.1.9/svg4everybody.min.js')}}"></script>
<script>
    svg4everybody();
</script>
<!-- font - fontawesome -->
<link rel="stylesheet" href="{{ asset('assets/them/vendor/fontawesome-5.6.3/css/all.min.css')}}">
<!-- font - stroyka -->
<link rel="stylesheet" href="{{ asset('assets/them/fonts/stroyka/stroyka.css')}}">

@stack('styles')

resources/views/web/them/partials/main.blade.php
<div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
{{--            <div class="page-header__breadcrumb">--}}
{{--                <nav aria-label="breadcrumb">--}}
{{--                    <ol class="breadcrumb">--}}
{{--                        <li class="breadcrumb-item"><a href="index.html">خانه</a>--}}
{{--                            <svg class="breadcrumb-arrow" width="6px" height="9px">--}}
{{--                                <use xlink:href="{{ asset('assets/them/images/sprite.svg#arrow-rounded-right-6x9')}}"></use>--}}
{{--                            </svg>--}}
{{--                        </li>--}}
{{--                        <li class="breadcrumb-item"><a href="">تکه مسیر</a>--}}
{{--                            <svg class="breadcrumb-arrow" width="6px" height="9px">--}}
{{--                                <use xlink:href="{{ asset('assets/them/images/sprite.svg#arrow-rounded-right-6x9')}}"></use>--}}
{{--                            </svg>--}}
{{--                        </li>--}}
{{--                        <li class="breadcrumb-item active" aria-current="page">سبد خرید</li>--}}
{{--                    </ol>--}}
{{--                </nav>--}}
{{--            </div>--}}
            <div class="page-header__title">
                <h1>@section('title_page')@show</h1>
                <div>        @include('flash::message')
                </div>
            </div>
        </div>
    </div>
    <div class="block-empty__body">
        @yield('content')
    </div>
</div>

resources/views/web/them/partials/mobileSiteHeader.blade.php
<header class="site__header d-lg-none">
    <div class="mobile-header mobile-header--sticky mobile-header--stuck">
        <div class="mobile-header__panel">
            <div class="container">
                <div class="mobile-header__body">
                    <button class="mobile-header__menu-button">
                        <svg width="18px" height="14px">
                            <use xlink:href="{{ asset('assets/them/images/sprite.svg#menu-18x14')}}"></use>
                        </svg>
                    </button>
                    <a class="mobile-header__logo" href="index.html">
                        <svg xmlns="http://www.w3.org/2000/svg" width="120px" height="20px">
                            <path d="M118.5,20h-1.1c-0.6,0-1.2-0.4-1.4-1l-1.5-4h-6.1l-1.5,4c-0.2,0.6-0.8,1-1.4,1h-1.1c-1,0-1.8-1-1.4-2l1.1-3
                                 l1.5-4l3.6-10c0.2-0.6,0.8-1,1.4-1h1.6c0.6,0,1.2,0.4,1.4,1l3.6,10l1.5,4l1.1,3C120.3,19,119.5,20,118.5,20z M111.5,6.6l-1.6,4.4
                                 h3.2L111.5,6.6z M99.5,20h-1.4c-0.4,0-0.7-0.2-0.9-0.5L94,14l-2,3.5v1c0,0.8-0.7,1.5-1.5,1.5h-1c-0.8,0-1.5-0.7-1.5-1.5v-17
                                 C88,0.7,88.7,0,89.5,0h1C91.3,0,92,0.7,92,1.5v8L94,6l3.2-5.5C97.4,0.2,97.7,0,98.1,0h1.4c1.2,0,1.9,1.3,1.3,2.3L96.3,10l4.5,7.8
                                 C101.4,18.8,100.7,20,99.5,20z M80.3,11.8L80,12.3v6.2c0,0.8-0.7,1.5-1.5,1.5h-1c-0.8,0-1.5-0.7-1.5-1.5v-6.2l-0.3-0.5l-5.5-9.5
                                 c-0.6-1,0.2-2.3,1.3-2.3h1.4c0.4,0,0.7,0.2,0.9,0.5L76,4.3l2,3.5l2-3.5l2.2-3.8C82.4,0.2,82.7,0,83.1,0h1.4c1.2,0,1.9,1.3,1.3,2.3
                                 L80.3,11.8z M60,20c-5.5,0-10-4.5-10-10S54.5,0,60,0s10,4.5,10,10S65.5,20,60,20z M60,4c-3.3,0-6,2.7-6,6s2.7,6,6,6s6-2.7,6-6
                                 S63.3,4,60,4z M47.8,17.8c0.6,1-0.2,2.3-1.3,2.3h-2L41,14h-4v4.5c0,0.8-0.7,1.5-1.5,1.5h-1c-0.8,0-1.5-0.7-1.5-1.5v-17
                                 C33,0.7,33.7,0,34.5,0H41c0.3,0,0.7,0,1,0.1c3.4,0.5,6,3.4,6,6.9c0,2.4-1.2,4.5-3.1,5.8L47.8,17.8z M42,4.2C41.7,4.1,41.3,4,41,4h-3
                                 c-0.6,0-1,0.4-1,1v4c0,0.6,0.4,1,1,1h3c0.3,0,0.7-0.1,1-0.2c0.3-0.1,0.6-0.3,0.9-0.5C43.6,8.8,44,7.9,44,7C44,5.7,43.2,4.6,42,4.2z
                                  M29.5,4H25v14.5c0,0.8-0.7,1.5-1.5,1.5h-1c-0.8,0-1.5-0.7-1.5-1.5V4h-4.5C15.7,4,15,3.3,15,2.5v-1C15,0.7,15.7,0,16.5,0h13
                                 C30.3,0,31,0.7,31,1.5v1C31,3.3,30.3,4,29.5,4z M6.5,20c-2.8,0-5.5-1.7-6.4-4c-0.4-1,0.3-2,1.3-2h1c0.5,0,0.9,0.3,1.2,0.7
                                 c0.2,0.3,0.4,0.6,0.8,0.8C4.9,15.8,5.8,16,6.5,16c1.5,0,2.8-0.9,2.8-2c0-0.7-0.5-1.3-1.2-1.6C7.4,12,7,11,7.4,10.3l0.4-0.9
                                 c0.4-0.7,1.2-1,1.8-0.6c0.6,0.3,1.2,0.7,1.6,1.2c1,1.1,1.7,2.5,1.7,4C13,17.3,10.1,20,6.5,20z M11.6,6h-1c-0.5,0-0.9-0.3-1.2-0.7
                                 C9.2,4.9,8.9,4.7,8.6,4.5C8.1,4.2,7.2,4,6.5,4C5,4,3.7,4.9,3.7,6c0,0.7,0.5,1.3,1.2,1.6C5.6,8,6,9,5.6,9.7l-0.4,0.9
                                 c-0.4,0.7-1.2,1-1.8,0.6c-0.6-0.3-1.2-0.7-1.6-1.2C0.6,8.9,0,7.5,0,6c0-3.3,2.9-6,6.5-6c2.8,0,5.5,1.7,6.4,4C13.3,4.9,12.6,6,11.6,6
                                 z"></path>
                        </svg>
                    </a>
                    <div class="mobile-header__search">
                        <form class="mobile-header__search-form" action="">
                            <input class="mobile-header__search-input" name="search" placeholder="جستجو از میان 10,000 محصول" aria-label="Site search" type="text" autocomplete="off">
                            <button class="mobile-header__search-button mobile-header__search-button--submit" type="submit">
                                <svg width="20px" height="20px">
                                    <use xlink:href="{{ asset('assets/them/images/sprite.svg#search-20')}}"></use>
                                </svg>
                            </button>
                            <button class="mobile-header__search-button mobile-header__search-button--close" type="button">
                                <svg width="20px" height="20px">
                                    <use xlink:href="{{ asset('assets/them/images/sprite.svg#cross-20')}}"></use>
                                </svg>
                            </button>
                            <div class="mobile-header__search-body"></div>
                        </form>
                    </div>
                    <div class="mobile-header__indicators">
                        <div class="indicator indicator--mobile-search indicator--mobile d-sm-none">
                            <button class="indicator__button"><span class="indicator__area"><svg width="20px" height="20px"><use xlink:href="{{ asset('assets/them/images/sprite.svg#search-20')}}"></use></svg></span></button>
                        </div>
                        <div class="indicator indicator--mobile d-sm-flex d-none"><a href="wishlist.html" class="indicator__button"><span class="indicator__area"><svg width="20px" height="20px"><use xlink:href="{{ asset('assets/them/images/sprite.svg#heart-20')}}"></use></svg> <span class="indicator__value">0</span></span></a></div>
                        <div class="indicator indicator--mobile"><a href="cart.html" class="indicator__button"><span class="indicator__area"><svg width="20px" height="20px"><use xlink:href="{{ asset('assets/them/images/sprite.svg#cart-20')}}"></use></svg> <span class="indicator__value">3</span></span></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/web/them/partials/scripts.blade.php
<!-- BEGIN: Vendor JS-->
{{--<script src="{{ asset('assets/manegment/dashbord/users/vendors/js/vendors.min.js') }}"></script>--}}
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Theme JS-->

<!-- END: Theme JS-->


@stack('scripts')